### ISSUE TITLE
Encapsulation section.  Reference to tasks.length

### ISSUE THREAD

**Issue by dholtz** [scalazone/scala#45]
In the following lecture/section:
https://scala.zone/courses/scala-beginner/templates/objects

```
object Project extends ProjectDef:
  val tasks: List[Task] = List(Setup, Core, Refinement, Cleanup)
  def todo: Int = tasks.count(!_.done) 

println(s"There are ${Project.todo} tasks to do.")
```

> we need the count method which operates on the Task elements of the List called tasks, hence we call **_tasks.length_**.

I don't see a call to `tasks.length`
This _could_ be confusing for people.

**Comment by propensive** [comment]
Yes, that's another good catch. I think it's meant to say `tasks.todo`. I'll take a closer look tomorrow.
