### ISSUE TITLE
Lazy Instantiation section, possible typo

### ISSUE THREAD

**Issue by dholtz** [scalazone/scala#46]
In section: https://scala.zone/courses/scala-beginner/templates/objects

**Lazy Instantiation**
```
That means that an object may be defined in our program, but it will exist as a "living" 
value on the heap until one of the running threads makes its first reference to it
```

Should this be:

"That means that an object may be defined in our program, but it will **not** exist as a "living" value on the heap until one of the running threads makes its first reference to it"

**Comment by propensive** [comment]
Yes! Well spotted, thank you!

**Comment by propensive** [comment]
Thanks to others for actually making this update after I forgot!
