### ISSUE TITLE
pattern matching bindings now use `as`

### ISSUE THREAD

**Issue by propensive** [scalazone/scala#50]
The new syntax for binding an identifier to a pattern is,
```
case id as {pattern} => ...
```

**Comment by dhodder** [comment]
N.B. the [Scala 3.0.0-M3 release](https://dotty.epfl.ch/blog/2020/12/18/scala3-m3.html) has dropped `as`, reverting back to the Scala 2 `@` syntax.

**Comment by propensive** [comment]
Thanks for the reminder! I was slow to make the updates anyway, but I can close this now.
